### ISSUE TITLE
Modal 需要更多 story 实例以提供使用的线索

### ISSUE THREAD

**Issue by franco-chan** [OneKeyHQ/fe-ui-components#105]
因为 Modal 组件包含了 Header、Body、Footer 三个子组件，所以隐藏的 prop 的信息无法在 props 列表里面查看。

可以提供更多的示例，比如自定义 header 里面的 title，以及自定义 footer，帮助其他成员更好了解该组件所能做的事。

**Comment by AmagiDDmxh** [comment]
TODO:

- [ ] 删掉外层的 UIProvider 来修复 Nested Modal 无法获得业务提供的 translations 问题
- [ ] Modal.Header 的 as 使用 header，footer 同理
- [ ] 分别解耦出 Modal / Overlay / Content / Header / Body / Footer / CloseButton

参考：
- https://chakra-ui.com/docs/overlay/modal#usage
