### ISSUE TITLE
Modal 加强

### ISSUE THREAD

**Issue by franco-chan** [OneKeyHQ/fe-ui-components#44]
<img width="561" alt="CleanShot 2021-09-06 at 21 59 53@2x" src="https://user-images.githubusercontent.com/23469879/132228709-6799b93f-bb70-4725-9abb-1a4056d395a1.png">

如图所示，被聚焦的是第一个可点击元素 close button。在 [headlessui](https://headlessui.dev/react/dialog) 文档可以查看到调控初始化聚焦元素的相关方法。

**Comment by AmagiDDmxh** [comment]
Modal TODO
- [ ] 支持内联 Modal
- [ ] 支持 或 更好的 大小控制，而不是永远的 max-w-lg
- [ ] First focus 元素

**Comment by AmagiDDmxh** [comment]
Done by #87
