### ISSUE TITLE
组件命名冲突

### ISSUE THREAD

**Issue by franco-chan** [OneKeyHQ/fe-ui-components#57]
我看到有一个 `NFTCard` 组件，它的命名跟如图所示的组件重复：
<img width="299" alt="CleanShot 2021-09-10 at 11 08 51@2x" src="https://user-images.githubusercontent.com/23469879/132793348-5207484b-8374-4be3-a72a-ad7adc20d8d7.png">
是否有更好的解决方案？如图的组件也不一定要叫 `nftCard`，我觉得两个组件改任意一个都行。

**Comment by loatheb** [comment]
可以叫 `NFTGalleryItem` 之类的，之前的 card 如果先合入了就改后面的名字吧
