### ISSUE TITLE
Card 组件在 small breakpoint 出现内边距收缩现象

### ISSUE THREAD

**Issue by AmagiDDmxh** [OneKeyHQ/fe-ui-components#80]
<img width="777" alt="CleanShot 2021-09-14 at 13 24 38@2x" src="https://user-images.githubusercontent.com/22388514/133199797-068e43b9-b328-4bfa-b37f-9050523a9b4a.png">

**Comment by franco-chan** [comment]
已修复，稍后 push

**Comment by AmagiDDmxh** [comment]
Fix by #86
