### ISSUE TITLE
Button 使 leading / trailing 部分可自定义

### ISSUE THREAD

**Issue by AmagiDDmxh** [OneKeyHQ/fe-ui-components#96]
场景：
当 TransactionHistoryButton 出现 pending 交易的情况
<img width="389" alt="CleanShot 2021-09-16 at 20 10 43@2x" src="https://user-images.githubusercontent.com/22388514/133609803-7de3563d-3324-4814-aef5-354cb527e20d.png">
<img width="445" alt="CleanShot 2021-09-16 at 20 12 04@2x" src="https://user-images.githubusercontent.com/22388514/133610004-5a0eb175-143a-4045-bb47-94e107f8e855.png">

可选方案：
使用 Card 加上 between 布局来实现

**Comment by franco-chan** [comment]
这里我们可能给 button 赋予太多的责任了。这个元素的结构较复杂，我个人建议是使用 card 来做，这样的话内容还可以跟 swap 上方的卡片对齐。

**Comment by franco-chan** [comment]
@AmagiDDmxh 可以
